### ISSUE TITLE
Offset on pop-up click area

### ISSUE THREAD

**Issue by gareins** [rokrupnik/bonar_cordova#13]
For now OK, but not 100%. Try it in browser...

**Comment by gareins** [comment]
Problem: transparency in the middle of pin icon. There the popup is not trigered if clicked on.

**Comment by rokrupnik** [comment]
Fixed with e848ad1d45e7b2c1e04504143325b24938609699 and ec23077809d542b31321dd155d6839629604bab9. Just filled inner transparent circle. Have tried with a transparent fill, but it wasn't working.

Closing for now.
