### ISSUE TITLE
Uporabi Cordova plugin za dostop do časa naprave

### ISSUE THREAD

**Issue by rokrupnik** [rokrupnik/bonar_cordova#5]

**Comment by gareins** [comment]
Namen?

**Comment by rokrupnik** [comment]
Prikaz odprtih/zaprtih restavracij.

V V čet., 14. apr. 2016 ob 21:46 je oseba gareins notifications@github.com
napisala:

**Comment by gareins** [comment]
Sej tole vrze lokalni cas: 

`var d = new Date();`

Ne vem ce nucamo specialen plugin...

**Comment by rokrupnik** [comment]
true that... nisem na to mislil, ko sem prvic bral o Cordova pluginih in so se mi zdel res kul :P
