### ISSUE TITLE
Optimize map in general

### ISSUE THREAD

**Issue by gareins** [rokrupnik/bonar_cordova#8]

**Comment by gareins** [comment]
Did the clustering earlier in @422991b. ToDo is to actually use that data.

**Comment by rokrupnik** [comment]
ToDo: try out OpenLayers with clustering -> [link](http://openlayers.org/en/master/apidoc/ol.source.Cluster.html)

**Comment by rokrupnik** [comment]
[OL v3.15.1 docs](http://openlayers.org/en/v3.15.1/doc/)

**Comment by gareins** [comment]
Bravo :+1:
